### ISSUE TITLE
Put here 'compact' view of results

### ISSUE THREAD

**Issue by tripu** [w3c/wbs-design#68]
(@lcarcone, this is about Sysreq no. 12535.)

The kind of *compact* view of the results that we have modified in production (the one linked on that Sysreq ticket), is not here, in the GH repository. Or is it?

The closest we have is `qtypes-site-results.html`, but if I append the parameter (`qtypes-site-results.html?view=compact`), nothing changes on the page&hellip;

Do you think we can copy that page here, to keep consistency between what's in production, and this repository?

Thanks.

**Comment by lcarcone** [comment]
Hi Tripu,
The dispatch to the different modules according to the parameters is managed by the .htaccess file in the main WBS directory, I don't think we can have the same environment in github with static files.

In the branch 'table-header' [1] I created a light version of that page, in the file table-header.html. I used it to test the pluging 'fixedHeaderTable ', I managed to have it working for the 'Details' table (the header and the first column are fixed). If you think this work is interesting I can create a PR, otherwise you can copy this file in the main tree.
Note that I have I anonymized the personal infos of the responders (name, email, organization) as you didn't want to have such infos in github and I agree we should not display them.

Thanks,
Laurent

[1] https://github.com/w3c/wbs-design/tree/table-header

**Comment by tripu** [comment]
I already applied my fix to improve large tables in production (check out any &ldquo;compact view&rdquo;).

If it's not quick to *import* one of such pages (with anonymised data) in this repository, that's OK. It's no big deal.

Thank you anyway :)
