### ISSUE TITLE
UTF-8 errors

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/wbs-design#69]
I have had reports from two people so far saying they are getting UTF-8 errors trying to submit answers to https://www.w3.org/2002/09/wbs/35422/processfeedback/. Once is an outlier, twice is a trend. 

Details from one person:

>I am having trouble submitting a response to a WBS form from AGWG. I composed my lengthy answer in Windows Notepad, then pasted it into WBS form.  I get an error:
>
>"Your answers have NOT been registered because of the following errors:
>    The comment text provided for question 'Feedback on current decision policy' is not valid UTF-8.
>
>I manually deleted and replaced the line feeds which had no effect.  I still received the error.  I ran the answer through Notepad++ which has a Convert to UTF-8 option.  I still get the error message.

The other person did not provide context for the problem.

**Comment by lcarcone** [comment]
Hi Michael,

I think this problem is caused by the length of the response for that question.
WBS uses a complex regular expresion to check that a string is valid utf-8. There is an internal PHP limit for the use of such expressions and I guess it has been reached in those cases (the current limit works for buffer whose length is less than 2700 approximately).
I have increased that limit, could you ask the persons to retry to submit their response ? If it still fails, could you ask them to send us their response so that I can do more tests.
Increasing that limit might impact performance and memory on the server so we have to find the right balance.

HTH,
Laurent

**Comment by lcarcone** [comment]
Hi Michael,
Do you know if the two people who reported that they could not submit their answers were able to do it after my modification?

Thank you

**Comment by michael-n-cooper** [comment]
I don't have any data about that. I wasn't aware you had made a change, and don't know that the people with difficult submitting answers were aware either. They don't appear to have tried again.

**Comment by michael-n-cooper** [comment]
I just saw that you had commented earlier in this issue a week ago. I didn't receive a notification from GitHub about it, so I didn't see it until just now. I'll ask the people to resubmit.

**Comment by michael-n-cooper** [comment]
One person has tried resubmitting their input and succeeded this time. The other may not get to it quickly based on my experience, so I think we'll take this as evidence of being fixed.

And yes, at least in the Accessibility Guidelines WG, people are prone to long responses in WBS sometimes. I didn't realize it had a particular performance impact. It would be good to find a way to allow long responses, or failing that, put a warning about the issue in surveys, ideally supported by a client side script that could inform if you've gone over the limit.

**Comment by lcarcone** [comment]
Hi Michael,

Great that the configuration change seems to have worked. We have not received any messages about slowness/errors since I made the change, I guess it has no impact on performance.
I agree we should improve the error message and put a warning about this issue. If I have time I'd like to add more interactivity in WBS, (a message indicating that a limit has been exceeded is a good example).

Thanks,
Laurent
